

spring:
  profiles:
    active: dev # ????? dev ???? ??
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: file:src/main/resources/templates/ # ???? ?? ??(? ??? ?? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/gramgram?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: qndnjs753!
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ????(??? ???? ??? ?)
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        show_sql: true
        format_sql: true
        use_sql_comments: true